# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_count', models.IntegerField(verbose_name='Number of results')),
                ('result_ids', models.TextField(blank=True, verbose_name='ID list of results')),
            ],
            options={
                'verbose_name': 'search result',
                'verbose_name_plural': 'search results',
            },
        ),
        migrations.AlterModelOptions(
            name='searchfield',
            options={'verbose_name': 'search field', 'verbose_name_plural': 'search fields'},
        ),
    ]
