# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm', '0012_auto_20160601_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCaseCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldname', models.CharField(default=b'None', max_length=100, verbose_name='old name')),
                ('possibilities', models.CharField(max_length=500, verbose_name='possibilities')),
                ('change_validated', models.CharField(default=0, max_length=3, verbose_name='change validated')),
            ],
            options={
                'ordering': ['city'],
                'verbose_name': 'special case city',
                'verbose_name_plural': 'special case cities',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='city',
            name='district_id',
            field=models.CharField(max_length=10, null=True, verbose_name='district id'),
        ),
        migrations.AddField(
            model_name='city',
            name='geonames_valid',
            field=models.BooleanField(default=False, verbose_name='is geonames valid'),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='zip code'),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='entity',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='entity',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='specialcasecity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crm.City'),
        ),
    ]
