# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm', '0013_auto_20160726_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo_url',
            field=models.CharField(max_length=300, null=True, verbose_name='photo url'),
        ),
    ]
