# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm', '0014_auto_20160726_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Email address')),
                ('date', models.CharField(max_length=200, verbose_name='Sending date')),
                ('error', models.CharField(max_length=200, verbose_name='Error')),
            ],
        ),
        migrations.CreateModel(
            name='MailImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(max_length=200, verbose_name='Email address')),
                ('date', models.DateField(default=None, verbose_name='Date')),
                ('content', models.CharField(default=b'', max_length=10000, verbose_name='Content')),
                ('imported_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='imported by')),
            ],
        ),
        migrations.CreateModel(
            name='MailProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('imapServer', models.CharField(max_length=100, verbose_name='imap server')),
                ('port', models.IntegerField(default=993, verbose_name='imap port')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'mail provider',
                'verbose_name_plural': 'mail providers',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='valid_email',
            field=models.BooleanField(default=True, verbose_name='valid email address'),
        ),
        migrations.AddField(
            model_name='mailimport',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crm.MailProvider'),
        ),
    ]
