# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0015_auto_20160726_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errormailaddress',
            options={'verbose_name': 'mail error', 'verbose_name_plural': 'mail errors'},
        ),
        migrations.AlterModelOptions(
            name='mailimport',
            options={'verbose_name': 'mail import', 'verbose_name_plural': 'mail imports'},
        ),
    ]
