# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0016_auto_20160726_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailImportAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='email address')),
                ('lastname', models.CharField(blank=True, default='', max_length=200, verbose_name='lastname')),
                ('firstname', models.CharField(blank=True, default='', max_length=200, verbose_name='firstname')),
            ],
            options={
                'verbose_name': 'mail import address',
                'verbose_name_plural': 'mail import addresses',
            },
        ),
        migrations.RemoveField(
            model_name='mailimport',
            name='content',
        ),
        migrations.AddField(
            model_name='mailimportaddress',
            name='mail_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crm.MailImport', verbose_name='mail import'),
        ),
    ]
