# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0017_auto_20160727_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo_url',
            field=models.CharField(blank=True, default=b'', max_length=300, null=True, verbose_name='photo url'),
        ),
    ]
