# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    """Assign fav_lang from favorite_language"""
    contact_model = apps.get_model("Crm", "Contact")
    language_model = apps.get_model("Crm", "Language")

    for code, name in settings.LANGUAGES:
        language_model.objects.create(name=name, code=code)

    for contact in contact_model.objects.exclude(favorite_language=''):
        try:
            contact.fav_lang = language_model.objects.get(code=contact.favorite_language)
            contact.save()
        except language_model.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0018_auto_20160727_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='fav_lang',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.Language', verbose_name='favorite language'),
        ),
        migrations.RunPython(forwards),
    ]
