# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0019_auto_20160727_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='favorite_language',
        ),
    ]
